### ISSUE TITLE
ActionController::UrlGenerationError when open Test cases page

### ISSUE THREAD

**Issue by wallhided** [dermitdemwolf/redcase-redmine-4.0.x#1]
Completed 200 OK in 45ms (Views: 2.0ms | ActiveRecord: 23.4ms)
Completed 500 Internal Server Error in 3363ms (ActiveRecord: 1065.6ms)

ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"redcase/wiki", :id=>"YouTube", :parent=>nil, :project_id=>#<Project id: 1, name: "MyProject", description: "Application MyProject", homepage: "", is_public: false, parent_id: nil, created_on: "2013-06-26 10:33:51", updated_on: "2013-06-28 03:23:22", identifier: "myproject", status: 1, lft: 3, rgt: 6, inherit_members: false, default_version_id: nil, easy_baseline_for_id: nil, default_assigned_to_id: nil>, :version=>nil}):

app/helpers/application_helper.rb:922:in `block in parse_wiki_links'
app/helpers/application_helper.rb:881:in `gsub!'
app/helpers/application_helper.rb:881:in `parse_wiki_links'
app/helpers/application_helper.rb:793:in `block (2 levels) in textilizable'
app/helpers/application_helper.rb:792:in `each'
app/helpers/application_helper.rb:792:in `block in textilizable'
app/helpers/application_helper.rb:813:in `parse_non_pre_blocks'
app/helpers/application_helper.rb:791:in `textilizable'
plugins/redcase/app/models/test_case.rb:126:in `to_json'
plugins/redcase/app/models/test_suite.rb:40:in `block in to_json'
plugins/redcase/app/models/test_suite.rb:39:in `collect'
plugins/redcase/app/models/test_suite.rb:39:in `to_json'
plugins/redcase/app/models/test_suite.rb:54:in `block in to_json'
plugins/redcase/app/models/test_suite.rb:53:in `collect'
plugins/redcase/app/models/test_suite.rb:53:in `to_json'
plugins/redcase/app/controllers/redcase/testsuites_controller.rb:10:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by dermitdemwolf** [comment]
I am not a redmine/ruby developer. But I have the feeling, that there is an issue with your project setup. Maybe you need a wiki or your wiki is different than my one. So you could try if it works without wikimodeule.

**Comment by wallhided** [comment]
This plugin worked on Redmine 3.x version , and after upgrading redmine to 4.x and installing this project (redcase-redmine-4.0.x) the problem appeared.

**Comment by wallhided** [comment]
One of my pages in Wiki callled Youtube (see error text) and this page contains links.
So where I can open issue?

**Comment by wallhided** [comment]
Disabling of wiki module helped me, but I cannot use Redmine without it.

**Comment by dermitdemwolf** [comment]
the problem is, that we also shifted from redmine 3 to redmine 4. Redcase didn't work anymore. So we decided to contact a ruby developer, who made us this custom solution, which works fine for us. But I think there is not really somebody who will answer you on the issues. 
But that's the developer, who helped us:
https://github.com/bilel-kedidi/

**Comment by dermitdemwolf** [comment]
And we decided to share the solution, so anybody could try it too. But we can't really fix open issues. I am sorry.

**Comment by wallhided** [comment]
Thank you for fast response!

**Comment by wallhided** [comment]
https://bitbucket.org/bugzinga/redcase/pull-requests/56/do-not-crash-on-wiki-links-see-98/diff
This commit fixed that issue.
